config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  # devise_for :contractors, controllers: { registrations: "contractors/registrations" }
  # devise_for :requesters

  resources :tasks do
    resources :bids, only: [:new, :create, :index, :show]
  end

  resources :charges, only: [:create]

  root controller: :home, action: :index
  resources :home, only: [:index]

  get '/bid_terms', to: 'bids#bid_terms_doc', as: 'bid_terms_doc'
  post '/winning_bid', to: 'bids#winning_bid', as: 'winning_bid'
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :user
  belongs_to :task
  validates_presence_of :quote
  validates :terms_of_service, acceptance: { message: 'Please confirm you have read the Terms and Conditions' }
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  
  def create
    @task = Task.find(params[:task_id])
    if Bid.where(user: current_user).where(task: @task).exists?
      redirect_to task_path(@task)
      flash[:notice] = 'Sorry you can only make one offer. Please update your current offer if you need to change your bid'
    elsif bid_params[:quote] == ''
      flash[:notice] = 'Please quote an amount'
      redirect_to task_path(@task)
    elsif bid_params[:terms_of_service] == '0'
      flash[:notice] = 'Please confirm you have read the Terms and Conditions'
      redirect_to task_path(@task)
    else
      @bid = @task.bids.new(bid_params)
      @bid.user = current_user
      @task.status = 'Bidding'
      @bid.save
      @task.save
      redirect_to task_path(@task)
      flash[:notice] = 'Offer Made!'
    end
  end

  def show
    @task = Task.find(params[:task_id])
    @bid = Bid.find(params[:id])
  end

  def bid_terms_doc
    render layout: 'terms.html.haml'
  end

  def winning_bid
    @task = Task.find(params[:task_id])
    @bid = Bid.find(params[:bid_id])
    if params[:commit] == "Cancel"
      redirect_to task_path(@task)
    elsif params[:tos_accept_bid] == nil
      flash[:notice] = 'You need to check the box to accept the terms and conditions before a bid can be accepted.'
      redirect_to task_bid_path(@task, @bid)
    elsif params[:commit] == "OK"
      @task.status = 'Contracted'
      @task.save
      @bid.winning_bid = 1
      @bid.winning_bid_date = DateTime.now
      @bid.save
      flash[:notice] = 'You now have an agreement for this task. Congratulations!'
      redirect_to task_bid_path(@task, @bid)
    else
      flash[:notice] = "Please contact system administrator"
      redirect_to task_bid_path(@task, @bid)
    end
  end

  private

  def bid_params
    params.require(:bid).permit(:quote, :task_id, :terms_of_service)
  end
end

app/views/bids/bid_terms_doc.html.haml
%body
  #wrapper
    %header#header
      .container
        = link_to (image_tag('taskr.png')), root_path, class: 'navbar-brand', width:"117", height:"39"
        %nav#nav.navbar.navbar-collapsed-sm.navbar-default{role: "navigation"}
          .navbar-header
            %button.navbar-toggle{"data-target" => ".navbar-header-collapse", "data-toggle" => "collapse", type: "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
          .collapse.navbar-collapse.navbar-header-collapse
            %ul.nav.navbar-nav.navbar-right
              %li.active.dropdown
                = link_to  new_task_path, class: 'dropdown-toggle', "data-delay" => "50" do
                  %span Post new task
              %li.dropdown
                = link_to  tasks_path( {type: 'all'}), class: 'dropdown-toggle', "data-delay" => "50" do
                  %span Current Available Tasks
              %li.dropdown
                = link_to  root_path, class: 'dropdown-toggle', "data-delay" => "50" do
                  %span Home
              - if user_signed_in? && current_user.contractor?
                %li.dropdown
                  = link_to  edit_user_registration_path, class: 'dropdown-toggle', "data-delay" => "50" do
                    %span My Profile
                %li.dropdown
                  = link_to  destroy_user_session_path, method: :delete, class: 'dropdown-toggle', "data-delay" => "50" do
                    %span Log Out
              - elsif user_signed_in? && current_user.requester?
                %li.dropdown
                  = link_to  tasks_path({type: 'requester'}), class: 'dropdown-toggle', "data-delay" => "50" do
                    %span View My Tasks
                %li.dropdown
                  = link_to  destroy_user_session_path, method: :delete, class: 'dropdown-toggle', "data-delay" => "50" do
                    %span Log Out
              - else
                %li.dropdown
                  = link_to '#', class: 'dropdown-toggle', "data-delay" => "50", "data-hover" => "dropdown", "data-toggle" => "dropdown" do
                    %span
                      Contractor
                      %i.fa.fa-angle-down
                  %ul.dropdown-menu{role: "menu"}
                    %li
                      = link_to 'Contractor Sign Up', new_user_registration_path({ role: "contractor" })
                    %li
                      = link_to 'Contractor Log In', new_user_session_path
                %li.dropdown
                  = link_to '#', class: 'dropdown-toggle', "data-delay" => "50", "data-hover" => "dropdown", "data-toggle" => "dropdown" do
                    %span
                      Requester
                      %i.fa.fa-angle-down
                  %ul.dropdown-menu{role: "menu"}
                    %li
                      = link_to 'Requester Sign Up', new_user_registration_path({ role: "requester" })
                    %li
                      = link_to 'Requester Log In', new_user_session_path

    #main{role: "main"}
      #main-content-header
        .container
          .row
            .col-sm-12
              %h1.title
                Terms & Conditions


  #main-content
    .container
      .row
        %p Terms and Conditons when placing a bid or accepting a bid.
        %p Revision 0.0 Date 2017-06-18
        %p Close this window to go back to the previous page

app/views/bids/show.html.haml
%body
  #wrapper
    %header#header
      .container
        = link_to (image_tag('taskr.png')), root_path, class: 'navbar-brand', width:"117", height:"39"
        %nav#nav.navbar.navbar-collapsed-sm.navbar-default{role: "navigation"}
          .navbar-header
            %button.navbar-toggle{"data-target" => ".navbar-header-collapse", "data-toggle" => "collapse", type: "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
          .collapse.navbar-collapse.navbar-header-collapse
            %ul.nav.navbar-nav.navbar-right
              %li.active.dropdown
                = link_to  new_task_path, class: 'dropdown-toggle', "data-delay" => "50" do
                  %span Post new task
              %li.dropdown
                = link_to  tasks_path( {type: 'all'}), class: 'dropdown-toggle', "data-delay" => "50" do
                  %span Current Available Tasks
              %li.dropdown
                = link_to  root_path, class: 'dropdown-toggle', "data-delay" => "50" do
                  %span Home
              - if user_signed_in? && current_user.contractor?
                %li.dropdown
                  = link_to  edit_user_registration_path, class: 'dropdown-toggle', "data-delay" => "50" do
                    %span My Profile
                %li.dropdown
                  = link_to  destroy_user_session_path, method: :delete, class: 'dropdown-toggle', "data-delay" => "50" do
                    %span Log Out
              - elsif user_signed_in? && current_user.requester?
                %li.dropdown
                  = link_to  tasks_path({type: 'requester'}), class: 'dropdown-toggle', "data-delay" => "50" do
                    %span View My Tasks
                %li.dropdown
                  = link_to  destroy_user_session_path, method: :delete, class: 'dropdown-toggle', "data-delay" => "50" do
                    %span Log Out
              - else
                %li.dropdown
                  = link_to '#', class: 'dropdown-toggle', "data-delay" => "50", "data-hover" => "dropdown", "data-toggle" => "dropdown" do
                    %span
                      Contractor
                      %i.fa.fa-angle-down
                  %ul.dropdown-menu{role: "menu"}
                    %li
                      = link_to 'Contractor Sign Up', new_user_registration_path({ role: "contractor" })
                    %li
                      = link_to 'Contractor Log In', new_user_session_path
                %li.dropdown
                  = link_to '#', class: 'dropdown-toggle', "data-delay" => "50", "data-hover" => "dropdown", "data-toggle" => "dropdown" do
                    %span
                      Requester
                      %i.fa.fa-angle-down
                  %ul.dropdown-menu{role: "menu"}
                    %li
                      = link_to 'Requester Sign Up', new_user_registration_path({ role: "requester" })
                    %li
                      = link_to 'Requester Log In', new_user_session_path

    #main{role: "main"}
      #main-content-header
        .container
          .row
            .col-sm-12
              %h1.title
                Accept Bid
              %ol.breadcrumb
                %li
                  %a{ href: tasks_path({type: 'all'}) }
                    Back to all tasks

        #main-content
          .container
            .row
              .col-md-push-9.col-sm-push-8.col-sm-4.col-md-3
                %nav.sidebar
                  %button.btn.btn-block.btn-contrast.sidebar-toggle{"data-target" => ".sidebar-collapse", "data-toggle" => "collapse", type: "button"}
                    %span.sr-only Toggle navigation
                    %span.icon-bar
                    %span.icon-bar
                    %span.icon-bar
              .col-md-pull-3.col-sm-pull-4.col-sm-8.col-md-9
                .text-boxes
                  .row.text-box.text-box-title-above.text-box-big-image
                    .col-sm-12
                      %h3.title
                        %a{href: "#"} #{@task.name}
                      %hr.hr-half/
                      .toolbar
                        %a.btn.btn-link{href: "#"}
                          %i.fa.fa-arrows
                          %span Location: #{@task.location}
                        %a.btn.btn-link{href: "#"}
                          %i.fa.fa-calendar
                          %span #{@task.time_frame}
                        %a.btn.btn-link{href: "#"}
                          %i.fa.fa-cog
                          %span Status: #{@task.status}
                        - if @task.status == "Contracted"
                          %a.btn.btn-link{href: "#"}
                            %i.fa.fa-calendar
                            %span Contracted on: #{@bid.winning_bid_date}
                          %a.btn.btn-link{href: "#"}
                            %i.fa.fa-dollar
                            %span Winning Bid Amount: #{@bid.quote}
                        %a.btn.btn-link{href: "#"}
                          %i.fa.fa-dollar
                          %span Minimum Budget: #{@task.minimum_budget}
                        %a.btn.btn-link{href: "#"}
                          %i.fa.fa-dollar
                          %span Maximum Budget: #{@task.maximum_budget}
                        %a.btn.btn-link{href: "#"}
                          %i.fa.fa-cubes
                          %span Winning Contractor: #{@bid.user.email} - #{@bid.user.first_name} #{@bid.user.last_name}
                      %hr.hr-half/
                  .row.text-box
                    .col-sm-12
                      %h2 Description
                      %p #{@task.description}
                      %hr.hr-half/
                      .row
                        .col-sm-12
                          .row
                            = flash[:notice]
                            #comments.col-sm-12
                            - if @task.status == "Bidding"
                              %h3
                                Agreement:
                                .media
                                  .content
                                    .toolbar
                                    %p= "You are about to accept the bid from #{@bid.user.first_name} #{@bid.user.last_name}'s of #{@bid.quote}"
                                    %p If you are OK, please review terms and condition and check the box before pressing OK.
                                    %p Press Cancel to cancel the acceptance of the bid.
                              .row
                                %hr.hr-half/
                                = form_tag({controller: 'bids', action: 'winning_bid'}) do
                                  .form-group
                                    = check_box_tag :tos_accept_bid, id:'checkbox-inline input-inlineCheckbox2'
                                    = label_tag :tos_accept_bid, " I have read and agree to the "
                                    = link_to "Accept Bid Terms and Conditions", bid_terms_doc_path, target: :_blank
                                    = hidden_field_tag 'task_id', @task.id
                                    = hidden_field_tag 'bid_id', @bid.id
                                    = submit_tag "OK", class:'btn btn-contrast'
                                    = submit_tag "Cancel", class:'btn btn-contrast'
                            - if @task.status == 'Contracted'
                              %article
                                - if flash[:error].present?
                                  #error_explanation
                                    %p= flash[:error]
                                %label You're about to pay #{@bid.quote} $
                              = form_tag charges_path do
                                = hidden_field_tag :bid_id, @bid.id
                                %script.stripe-button{ src: 'https://checkout.stripe.com/checkout.js',
                                      data: {amount: @bid.quote*100, description: 'Taskr', key: Rails.configuration.stripe[:publishable_key], currency: 'sek'}}
                    #scroll-to-top.fade
                      %i.fa.fa-chevron-up